supply_chain_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      schema: "{{ env_var('BQ_DATASET') }}"
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      threads: 4

    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      schema: "{{ env_var('BQ_DATASET') }}"
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"

